package com.jayden.locationmanager.model.nmea

import com.jayden.locationmanager.model.nmea.indicator.FaaModeIndicator
import com.jayden.locationmanager.model.nmea.units.CrossTrackUnit
import com.jayden.locationmanager.model.nmea.units.RadiusUnit
import com.jayden.locationmanager.model.nmea.warning.CycleLockWarningFlag
import com.jayden.locationmanager.model.nmea.warning.GeneralWarningFlag

sealed interface NmeaMessage {
    data class AamEvent(
        val arrivalCircleEntered: Boolean?,
        val perpendicularPassed: Boolean?,
        val arrivalCircleRadius: Double?,
        val radiusUnit: RadiusUnit?,
        val waypointId: String?,
        val checksum: UByte?
    ) : NmeaMessage
    data class AlmEvent(
        val messageCount: Int?,
        val sentenceNumber: Int?,
        val satellitePrnNumber: Int?,
        val gpsWeekNumber: Int?,
        val svHealth: UInt?,
        val eccentricity: ULong?,
        val almanacReferenceTime: ULong?,
        val inclinationAngle: Long?,
        val rateOfRightAscension: Long?,
        val rootOfSemiMajorAxis: Long?,
        val argumentOfPerigee: Long?,
        val longitudeOfAscensionNode: Long?,
        val meanAnomaly: Long?,
        val f0ClockParam: Long?,
        val f1ClockParam: Long?,
        val checksum: UByte?
    ) : NmeaMessage
    data class ApaEvent(
        val generalWarning: GeneralWarningFlag?,
        val cycleLockWarning: CycleLockWarningFlag?,
        val crossTrackErrorMagnitude: Double?,
        val steeringDirection: SteeringDirection?,
        val crossTrackUnit: CrossTrackUnit?,
        val arrivalCircleEntered: Boolean?,
        val perpendicularPassed: Boolean?,
        val bearing: Double?,
        val bearingReference: CompassReference?,
        val destinationId: String?,
        val checksum: UByte?
    ) : NmeaMessage
    data class ApbEvent(
        val generalWarning: GeneralWarningFlag?,
        val cycleLockWarning: CycleLockWarningFlag?,
        val crossTrackErrorMagnitude: Double?,
        val steeringDirection: SteeringDirection?,
        val crossTrackUnit: CrossTrackUnit?,
        val arrivalCircleEntered: Boolean?,
        val perpendicularPassed: Boolean?,
        val bearingOrigin: Double?,
        val bearingOriginReference: CompassReference?,
        val destinationId: String?,
        val bearingPresent: Double?,
        val bearingPresentReference: CompassReference?,
        val bearingHeading: Double?,
        val bearingHeadingReference: CompassReference?,
        val checksum: UByte?
    ) : NmeaMessage
    data class BodEvent(
        val trueBearing: Double?,
        val magneticBearing: Double?,
        val destinationWaypointId: String?,
        val originWaypointId: String?,
        val checksum: UByte?
    ) : NmeaMessage
    data class BwcEvent(
        val utcTime: NmeaUtcTime?,
        val waypointLatitude: Double?,
        val waypointLongitude: Double?,
        val trueBearing: Double?,
        val magneticBearing: Double?,
        val distanceToWaypoint: Double?,
        val waypointId: String?,
        val faaModeIndicator: FaaModeIndicator?,
        val checksum: UByte?
    ) : NmeaMessage
    data class BwrEvent(
        val utcTime: NmeaUtcTime?,
        val waypointLatitude: Double?,
        val waypointLongitude: Double?,
        val trueBearing: Double?,
        val magneticBearing: Double?,
        val distanceToWaypoint: Double?,
        val waypointId: String?,
        val faaModeIndicator: FaaModeIndicator?,
        val checksum: UByte?
    ) : NmeaMessage
    data class BwwEvent(
        val trueBearing: Double?,
        val magneticBearing: Double?,
        val destinationWaypointId: String?,
        val originWaypointId: String?,
        val checksum: UByte?
    ) : NmeaMessage
    data class DbkEvent(
        val depthFeet: Double?,
        val depthMeters: Double?,
        val depthFathoms: Double?,
        val checksum: UByte?
    ) : NmeaMessage
    data class DbsEvent(
        val depthFeet: Double?,
        val depthMeters: Double?,
        val depthFathoms: Double?,
        val checksum: UByte?
    ) : NmeaMessage
    data class DbtEvent(
        val depthFeet: Double?,
        val depthMeters: Double?,
        val depthFathoms: Double?,
        val checksum: UByte?
    ) : NmeaMessage
    data class DptEvent(
        val waterDepthMeters: Double?,
        val transducerOffsetMeters: Double?,
        val maxRangeScale: Double?,
        val checksum: UByte?
    ) : NmeaMessage
    data class DtmEvent(
        val datumCode: String?,
        val datumSubcode: String?,
        val latitudeOffsetMinutes: Double?,
        val longitudeOffsetMinutes: Double?,
        val altitudeOffset: Double?,
        val datumName: String?,
        val checksum: UByte?
    ) : NmeaMessage
    data class FsiEvent(
        val transmittingFrequency: Double?,
        val receivingFrequency: Double?,
        val communicationsMode: String?,
        val powerLevel: UShort?,
        val checksum: UByte?
    ) : NmeaMessage
    data class GbsEvent(
        val utcTimeOfGnsFix: NmeaUtcTime?,
        val latitudeErrorMeters: Double?,
        val longitudeErrorMeters: Double?,
        val altitudeErrorMeters: Double?,
        val failedSatelliteId: Int?,
        val missedDetectionProbability: Double?,
        val failedSatelliteBiasMeters: Double?,
        val biasStandardDeviationMeters: Double?,
        val checksum: UByte?
    ) : NmeaMessage
    data class GgaEvent(
        val utcTimeOfReport: NmeaUtcTime?,
        val latitude: Double?,
        val longitude: Double?,
        val gpsQualityIndicator: GpsQualityIndicator?,
        val numOfSatellites: Int?,
        val horizontalPrecisionDilutionMeters: Double?,
        val antennaAltitudeSeaLevelMeters: Double?,
        val geoidalSeparationMeters: Double?,
        val gpsDataAgeDifference: Long?,
        val referenceStationId: Int?,
        val checksum: UByte?
    ) : NmeaMessage
    data class GllEvent(
        val latitude: Double?,
        val longitude: Double?,
        val utcTime: NmeaUtcTime?,
        val isValid: Boolean?,
        val faaModeIndicator: FaaModeIndicator?,
        val checksum: UByte?
    ) : NmeaMessage
    data class GnsEvent(
        val utcTime: NmeaUtcTime?,
        val latitude: Double?,
        val longitude: Double?,
        val modeIndicator: FaaModeIndicator?,
        val numOfSatellites: Int?,
        val horizontalPrecisionDilution: Double?,
        val antennaAltitudeSeaLevelMeters: Double?,
        val geoidalSeparationMeters: Double?,
        val dataAge: Long?,
        val referenceStationId: Int?,
        val navigationStatus: NavigationStatus?,
        val checksum: UByte?
    ) : NmeaMessage
    data class GrsEvent(
        val utcTime: NmeaUtcTime?,
        val residualType: ResidualType,
        val satelliteResidual1Meter: Double?,
        val satelliteResidual2Meter: Double?,
        val satelliteResidual3Meter: Double?,
        val satelliteResidual4Meter: Double?,
        val satelliteResidual5Meter: Double?,
        val satelliteResidual6Meter: Double?,
        val satelliteResidual7Meter: Double?,
        val satelliteResidual8Meter: Double?,
        val satelliteResidual9Meter: Double?,
        val satelliteResidual10Meter: Double?,
        val satelliteResidual11Meter: Double?,
        val satelliteResidual12Meter: Double?,
        val systemId: Int?,
        val signalId: Int?,
        val checksum: UByte?
    ) : NmeaMessage
    data class GsvEvent(
        val gsvSentencesToSend: Long?,
        val sentenceNumber: Int?,
        val satellitesInView: Int?,
        val satellite1PrnNumber: Int?,
        val satellite1ElevationDegrees: Double?,
        val satellite1AzimuthDegrees: Double?,
        val satellite1Snr: Double?,
        val satellite2PrnNumber: Int?,
        val satellite2ElevationDegrees: Double?,
        val satellite2AzimuthDegrees: Double?,
        val satellite2Snr: Double?,
        val satellite3PrnNumber: Int?,
        val satellite3ElevationDegrees: Double?,
        val satellite3AzimuthDegrees: Double?,
        val satellite3Snr: Double?,
        val satellite4PrnNumber: Int?,
        val satellite4ElevationDegrees: Double?,
        val satellite4AzimuthDegrees: Double?,
        val satellite4Snr: Double?,
        val checksum: UByte?
    ) : NmeaMessage
    data class ProprietaryEvent(
        val raw: String
    ) : NmeaMessage
    data class RawEvent(
        val raw: String
    ) : NmeaMessage
}